@startuml ContainerDiagramToBe
skinparam componentStyle uml2

component "EventsService" {
    [EventsAPI]
    [KafkaUI]
    queue Kafka
    interface "HTTP 83" as CollectorPort
    interface "HTTP 8081" as KafkaUIPort
}

component "EventsETLService" {
    [KafkaConsumer]
    database ClickHouse
    interface "HTTP 8123" as ClickHouseHTTPPort
    interface "HTTP 9000" as ClickHouseClientPort
}

[EventsAPI] --> Kafka : publishes events
[KafkaUI] --> Kafka
[KafkaConsumer] --> Kafka : consumes events
[KafkaConsumer] --> ClickHouse : stores events
CollectorPort --> [EventsAPI]
KafkaUIPort --> [KafkaUI]
ClickHouseHTTPPort --> ClickHouse
ClickHouseClientPort --> ClickHouse

@enduml