services:
  nginx:
    command: >
      sh -c "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    container_name: nginx
    image: nginx:stable-alpine3.20-slim
    restart: always
