services:
    elasticsearch:
      container_name: elasticsearch
      env_file:
        - envs/.elastic.env
      environment:
        - discovery.type=single-node # single instance
        - xpack.security.enabled=false # disable security checks
      healthcheck:
        test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
        interval: 30s
        timeout: 10s
        retries: 5
      image: elasticsearch:8.17.2
      expose: [9200]
      restart: always
      volumes:
        - elastic-data:/usr/share/elasticsearch/data

volumes:
  elastic-data:
