services:
  events-api:
    build:
      context: ../../services/events_api/src
      dockerfile: Dockerfile
    container_name: events-api
    env_file:
      - envs/.service.env
    healthcheck:
      test: curl -s http://$${API_HOST}:$${API_PORT}/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "83:8000"
    restart: always
